
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: jungle-music_development

test:
  <<: *default
  database: jungle-music_test

production:
  <<: *default
  database: jungle-music_production
  # username: jungle-music
  # password: <%= ENV['JUNGLE-MUSIC_DATABASE_PASSWORD'] %>
